channels:
  - conda-forge

dependencies:
#core libraries to run the machine
  - jupyterhub-singleuser>=3.0,<4.0
  - jupyter_contrib_nbextensions==0.5.1
  - jupyter-panel-proxy
  - jupyter-resource-usage
  - python=3.10
  - gh-scoped-creds
#Jupyterlab tools
  - jupyterlab-git
  - ipyleaflet
  - ipython
  - ipympl
  - ipytree
  - ipywidgets
  - nb_conda_kernels
  - nbstripout
#Scientific libraries
  - bottleneck
  - intake
  - geopandas
  - geopy
  - intake-xarray
  - numpy
  - pandas
  - parcels
  - pillow
  - scipy
  - seaborn
  - sparse
  - xarray
  - xarrayutils
  - xarray_leaflet
  - xgcm
  - xmip
  - xrft
  - zarr
#Remote storage access
  - adlfs
  - awscli
  - boto3
  - gcsfs
  - s3fs>0.5
  - tiledb-py
#geoscience libraries
  - argopy
  - ciso
  - earthdata
  - erddapy
  - esmpy
  - gcm_filters
  - geocube
  - gsw
  - intake-esm
  - intake-geopandas
  - intake-stac
  - metpy
  - pygeos
  - pyproj
  - pystac
  - pystac-client
  - satpy
  - xarray-spatial
  - xesmf
  - xskillscore
#file format/management
  - cfgrib
  - hdf5
  - h5netcdf
  - h5py
  - libnetcdf
  - nc-time-axis
  - netcdf4
#Distributed computing and ML
  - dask-ml
  - opencv
  - rechunker
  - scikit-image
  - scikit-learn
  - stackstac
#Visualization packages
  - datashader
  - descartes
  - cartopy >= 0.20.0
  - geogif
  - geoviews-core
  - gmt
  - holoviews
  - hvplot
  - matplotlib-base
  - panel
  - paraview
  - qgis
  - rasterio
  - rio-cogeo
  - rioxarray
#Miscellaneous
  - eofs
  - fsspec
  - gh
  - gfortran
  - git-lfs
  - kerchunk
  - libgfortran-ng
  - libxcb
  - lxml
  - lz4
  - moviepy
  - numcodecs
  - nodejs
  - param!=1.11.0
  - pip
  - pip:
    - cdsapi
    - utm
    - jupyterlab-s3-browser
    - jupyter-desktop-server==0.1.3
  - pyarrow
  - pycamhd
  - pydap
  - python-blosc
  - python-gist
  - python-lsp-server
  - pyopencl
  - timezonefinder
  - websockify>=0.10